export const blogPosts = [
  {
    id: 1,
    title: "Transforming Small Yards Into Green Retreats",
    image: "/blog3.jpeg",
    description: "Creative ideas for turning compact spaces into functional and beautiful landscapes.",
    category: "Landscaping",
    date: "2025-06-01",
    slug: "transforming-small-yards",
    content: "Discover how you can transform even the smallest outdoor space into a peaceful, usable garden retreat...",
  },
  {
    id: 2,
    title: "Choosing the Right Hardscape Materials",
    image: "/blog1.jpeg",
    description: "A guide to selecting pavers, stones, and features that blend with your outdoor design.",
    category: "Landscaping",
    date: "2025-05-22",
    slug: "hardscape-materials-guide",
    content: "Hardscaping plays a crucial role in defining structure. Here's how to choose materials that last and match your design...",
  },
  {
    id: 3,
    title: "Seasonal Landscape Planning Tips",
    image: "/blog3.jpeg",
    description: "Plan your landscape design around Kenya’s seasonal climate for year-round success.",
    category: "Landscaping",
    date: "2025-04-15",
    slug: "seasonal-landscape-tips",
    content: "Timing your planting and installations with the climate calendar can make a big difference in your results...",
  },

  // Gardening...
  {
    id: 4,
    title: "Top 5 Herbs to Grow at Home",
    image: "/blog1.jpeg",
    description: "Fresh, flavorful, and easy — these herbs thrive in small garden beds or pots.",
    category: "Gardening",
    date: "2025-06-10",
    slug: "herbs-to-grow-at-home",
    content: "Even a kitchen window can host thriving herbs. These are the best choices for beginners...",
  },
  {
    id: 5,
    title: "Composting 101: Turning Waste Into Gold",
    image: "/blog3.jpeg",
    description: "Learn how to start composting and boost your garden soil the natural way.",
    category: "Gardening",
    date: "2025-05-18",
    slug: "composting-101",
    content: "Turn kitchen waste into valuable compost with these simple methods and tools...",
  },
  {
    id: 6,
    title: "Garden Pests You Should Never Ignore",
    image: "/blog1.jpeg",
    description: "Identify and control the most common pests before they damage your plants.",
    category: "Nurseries",
    date: "2025-05-01",
    slug: "garden-pests-control",
    content: "From aphids to caterpillars, here's how to spot, stop, and prevent common garden invaders...",
  },

  // Sustainability...
  {
    id: 7,
    title: "Creating a Water-Efficient Garden",
    image: "/blog1.jpeg",
    description: "Techniques to reduce water usage without sacrificing plant health.",
    category: "Nurseries",
    date: "2025-06-15",
    slug: "water-efficient-garden",
    content: "Reduce your water bill and conserve resources with smart watering practices...",
  },
  {
    id: 8,
    title: "Eco-Friendly Landscaping Practices",
    image: "/blog1.jpeg",
    description: "Sustainable methods that protect the environment while beautifying your space.",
    category: "Nurseries",
    date: "2025-06-05",
    slug: "eco-friendly-landscaping",
    content: "Use native plants, compost, and eco-safe materials to build a landscape that gives back to nature...",
  },
  {
    id: 9,
    title: "Rainwater Harvesting for Your Backyard",
    image: "/blog1.jpeg",
    description: "Simple systems to capture and use rainwater for your garden or lawn.",
    category: "Advising",
    date: "2025-05-28",
    slug: "rainwater-harvesting",
    content: "Collecting rainwater can reduce runoff, save costs, and keep your garden green...",
  },
];
